services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shop
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: "redis:alpine"  # Лёгкий образ Redis
    ports:
      - "6379:6379"  # Мапинг порта для доступа извне (опционально)
    volumes:
      - ./redisdata:/data  # Персистентное хранение данных

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/shop
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  pgdata:

networks:
  backend:
